### ISSUE TITLE
DSI_VERSION replacement issue

### ISSUE THREAD

**Issue by jpvandara** [ODMDev/odm-dsi-docker#121]
Following the advanced usage of DSI documentation,
I want to customize a template,
 and use it in child dsi-runtime image (cf. Add custom templates into a specific image based on the dsi-runtime image).

I face the problem where _DSI_VERSION_ in server.xml is not replaced.

It seems that there is a missing step in the doc for this replacemement.

**Comment by orsinije** [comment]
Currently the DSI_VERSION var is replaced by its value in the server.xml when the image is build by a command in the Dockerfile so it does not apply for custom template. Eventually, the start.sh could also do it so it apply to any template whatever it is passed at runtime. It requires that the DSI version is passed as a env var of the docker container or an argument of the start command.

**Comment by jpvandara** [comment]
Note that this issue probably also exist for the volume case (Pass custom templates to a dsi-runtime docker container)

**Comment by remibm** [comment]
updated status: 
* DSI_VERSION value should be detected by start.sh out of used distrib (no more parameter in docker-compose.yaml)
* Substitution of _DSI_VERSION_ placeholder in template should be operated in start.sh at container creation instead of Dockerfile (solves volume use case)

**Comment by orsinije** [comment]
The output of runtime/wlp/bin/productInfo could be used by the 'start.sh' script to determine the version of DSI.
