### ISSUE TITLE
Need to rebrand dsi-runtime template

### ISSUE THREAD

**Issue by remibm** [ODMDev/odm-dsi-docker#99]
Candidate to be discussed and validated with OT : dsi-runtime-single?
This will avoid clashes with use of "dsi-runtime" as service name in sample cluster (to avoid using "container", which can be confusing in docker context).

**Comment by orsinije** [comment]
https://github.com/ODMDev/odm-dsi-docker/issues/100

We will see later for the naming of the container template for the cluster
